### ISSUE TITLE
Error thrown because of missing onTabReplaced

### ISSUE THREAD

**Issue by kenthompsonaustin** [SalesforceLabs/CaseTimer#3]
There is a handler for tabReplaced in the component, but there is no method for it in the controller. 
 It causes an error to be thrown any time the tabReplaced event occurs.  Unfortunately this means our company can't use it because the lightning errors being thrown are too disruptive.

<aura:handler event="lightning:tabReplaced" action="{! c.onTabReplaced }"/>

Stack trace: [LCE: consoleLayout2#processReplaceSubtabPage() - Failed to process request: jobLibrary - Job: processReplaceSubtabPage, Stage: tasks, Job failed. An error occurred while processing. LCE: workspace#updateTab() - Failed to update tab. tabId = ctab0_2 , Error: Unable to find action 'onTabReplaced' on the controller of CaseTimer19:serviceConsoleCaseTimerWrapper]
Object.<anonymous>()@https://static.lightning.force.com/cs34/auraCmpDef?aura.app=markup://one:one&_au=OYRNHg5YKSBSlNx_oA2NGg&_ff=DESKTOP&_l=true&_l10n=en_US&_c=false&_style=1620666853&_cssvar=true&_density=VIEW_TWO&force=closeRecord,listViewManagerDisplayDependencyConfiguration,listViewManagerDisplayDependencyItem,scopedActionModal,scopedModal,templateWorkspaceRendered&lightning=tabClosed,tabCreated,tabRefreshed,tabReplaced,unsavedChanges&objectManager=objectManagerLibrary&one=addWorkspaceTab,appNavEvent,appNavMenu,appNavMenuPanel,beforeTabFocusChange,closeWorkspace,consoleAccessibilityUtil,consoleAppCustomizationDefault,consoleAppCustomizationSetup,consoleEventBroker,consoleInlinePanel,consoleLayoutContainer2,consoleLi,consoleLogAction,consoleNav,consoleObjectHome,consoleObjectHomeFocus,consoleOverflowItem,consolePersistenceForceLogoutPlugin,consolePersistenceManager,consoleTab,consoleTabContainer,consoleTabContainerEvent,consoleTabDnD,consoleTabEvent,consoleTabItem,consoleTabNavigate,consoleTabScrollManager,consoleTabset,controlClickLibrary,getPanelManagerScopedContainerInfo,globalNav,isLeftContent,jobLibrary,lastWorkspaceClosed,leftContentWrapper,navItemDropdown,navItemDropdownMenuItem,navItemDropdownMenuItemSeparator,panelManagerScoped,refreshWorkspace,registerConsolePersistenceExtension,replaceWorkspaceTab,tabNavigationChange,toggleEditPage,updateWorkspaceTab,workspace,workspace2,workspaceCollection,workspaceTabEvent,workspaceTabWrapper&onesetup=breadcrumbChange,setupSearchInputDataProvider,setupSearchInputDesktop,setupSearchRequest&reports=editReportEvent&salesforceIdentity=appLauncherHeader&_uid=396928768:563:6

**Comment by gumJanDi** [comment]
Hi @kenthompsonaustin, have you check that you are accessing component using any service console application?
Try opening same page into any console application.

**Comment by gumJanDi** [comment]
Hi @kenthompsonaustin, 

I recently came across this package. and yes that are some prerequistics that we need to follow in order to use this app. 
Go through theur manual once. --> https://quip.com/kcHiAgqLWdg1

Also on your issue I can say that -- try opening record page (for which you have added this component) in any service console application you have.

**Comment by kenthompsonaustin** [comment]
Thanks for following up.  I ended up corresponding with Anika and she was able to fix the code and create version 1.8 of the package at the end of January.
